/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorTrabajador;
import javax.swing.JOptionPane;
import modelo.Trabajador;

/**
 *
 * @author Alfonso
 */
public class AgregarTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form AgregarTrabajador
     */
    public AgregarTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    public void limpiarTodo(){
        txt_nombreTrabajador.setText("");
        txt_apellidoTrabajador.setText("");
        txt_nacionalidad.setText("");
        cbb_anioNacimiento.setSelectedIndex(0);
        cbb_diaNacimiento.setSelectedIndex(0);
        cbb_mesNacimiento.setSelectedIndex(0);
        grupoSexo.clearSelection();
        txt_rutTrabajador.setText("");
        txt_dvRutTrabajador.setText("");
        txt_nombreTrabajador.requestFocus();
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSexo = new javax.swing.ButtonGroup();
        lbl_agregarTrabajador = new javax.swing.JLabel();
        img_cafeCorazon = new javax.swing.JLabel();
        lbl_pilisCoffee = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        lbl_fecNacimiento = new javax.swing.JLabel();
        txt_nombreTrabajador = new javax.swing.JTextField();
        txt_apellidoTrabajador = new javax.swing.JTextField();
        cbb_diaNacimiento = new javax.swing.JComboBox<>();
        lbl_dia = new javax.swing.JLabel();
        cbb_mesNacimiento = new javax.swing.JComboBox<>();
        lbl_mes = new javax.swing.JLabel();
        lbl_anio = new javax.swing.JLabel();
        cbb_anioNacimiento = new javax.swing.JComboBox<>();
        lbl_nacionalidad = new javax.swing.JLabel();
        txt_nacionalidad = new javax.swing.JTextField();
        btn_limpiar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        rbtn_masculino = new javax.swing.JRadioButton();
        rbtn_femenino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_rut = new javax.swing.JLabel();
        txt_rutTrabajador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_dvRutTrabajador = new javax.swing.JTextField();

        grupoSexo.add(rbtn_femenino);
        grupoSexo.add(rbtn_masculino);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbl_agregarTrabajador.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_agregarTrabajador.setText("Agregar Trabajador");

        img_cafeCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafeHeart.png"))); // NOI18N

        lbl_pilisCoffee.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_pilisCoffee.setForeground(new java.awt.Color(153, 51, 255));
        lbl_pilisCoffee.setText("Pili's Coffee");
        lbl_pilisCoffee.setMaximumSize(new java.awt.Dimension(1080, 1920));

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");

        lbl_apellido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_apellido.setText("Apellido:");

        lbl_fecNacimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecNacimiento.setText("Fecha de nacimiento:");

        cbb_diaNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cbb_diaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_diaNacimientoActionPerformed(evt);
            }
        });

        lbl_dia.setText("Día");

        cbb_mesNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cbb_mesNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_mesNacimientoActionPerformed(evt);
            }
        });

        lbl_mes.setText("Mes");

        lbl_anio.setText("Año");

        cbb_anioNacimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007" }));
        cbb_anioNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_anioNacimientoActionPerformed(evt);
            }
        });

        lbl_nacionalidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nacionalidad.setText("Nacionalidad:");

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        rbtn_masculino.setText("Masculino");

        rbtn_femenino.setText("Femenino");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Sexo:");

        lbl_rut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_rut.setText("Rut (sin puntos):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("-");

        txt_dvRutTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dvRutTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombre)
                            .addComponent(lbl_apellido)
                            .addComponent(txt_nombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_apellidoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_rut)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_rutTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dvRutTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtn_masculino)
                                .addGap(18, 18, 18)
                                .addComponent(rbtn_femenino))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(img_cafeCorazon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fecNacimiento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbb_diaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbb_mesNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbb_anioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_dia)
                                        .addGap(44, 44, 44)
                                        .addComponent(lbl_mes)
                                        .addGap(36, 36, 36)
                                        .addComponent(lbl_anio)))
                                .addGap(158, 158, 158)
                                .addComponent(lbl_pilisCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_agregarTrabajador)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_nacionalidad)
                            .addComponent(txt_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img_cafeCorazon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_pilisCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_agregarTrabajador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_rut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rutTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_dvRutTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(lbl_apellido)
                        .addGap(11, 11, 11)
                        .addComponent(txt_apellidoTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtn_masculino)
                            .addComponent(rbtn_femenino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_fecNacimiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dia)
                            .addComponent(lbl_mes)
                            .addComponent(lbl_anio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbb_diaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_mesNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_anioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nacionalidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbb_diaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_diaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_diaNacimientoActionPerformed

    private void cbb_mesNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_mesNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_mesNacimientoActionPerformed

    private void cbb_anioNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_anioNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_anioNacimientoActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        
        this.limpiarTodo();
        
        
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        if(txt_nombreTrabajador.getText().equals("")||txt_apellidoTrabajador.getText().equals("")||
            txt_nacionalidad.getText().equals("")||txt_rutTrabajador.getText().equals("")||
            txt_dvRutTrabajador.getText().equals("")||grupoSexo.getSelection()==null||
            cbb_diaNacimiento.getSelectedItem().equals("-")||cbb_mesNacimiento.getSelectedItem().equals("-")||
            cbb_anioNacimiento.getSelectedItem().equals("-")){
            JOptionPane.showMessageDialog(this, "DEBE LLENAR TODOS LOS CAMPOS");
        }
        else{
            Trabajador trabajador = new Trabajador();
            trabajador.setNombre(txt_nombreTrabajador.getText());
            trabajador.setApellido(txt_apellidoTrabajador.getText());
            trabajador.setNacionalidad(txt_nacionalidad.getText());
            trabajador.setRut(txt_rutTrabajador.getText());
            trabajador.setDv_rut(txt_dvRutTrabajador.getText());
            if(rbtn_femenino.isSelected())
                trabajador.setSexo('F');
            else 
                trabajador.setSexo('M');

            trabajador.setFechaNacimiento((String)
                    cbb_diaNacimiento.getSelectedItem()+'-'+
                    cbb_mesNacimiento.getSelectedItem()+'-'+
                    cbb_anioNacimiento.getSelectedItem());
            ControladorTrabajador nuevoTrabajador = new ControladorTrabajador();
            nuevoTrabajador.agregarTrabajador(trabajador, this);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_dvRutTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dvRutTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dvRutTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JComboBox<String> cbb_anioNacimiento;
    private javax.swing.JComboBox<String> cbb_diaNacimiento;
    private javax.swing.JComboBox<String> cbb_mesNacimiento;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel img_cafeCorazon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_agregarTrabajador;
    private javax.swing.JLabel lbl_anio;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_dia;
    private javax.swing.JLabel lbl_fecNacimiento;
    private javax.swing.JLabel lbl_mes;
    private javax.swing.JLabel lbl_nacionalidad;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_pilisCoffee;
    private javax.swing.JLabel lbl_rut;
    private javax.swing.JRadioButton rbtn_femenino;
    private javax.swing.JRadioButton rbtn_masculino;
    private javax.swing.JTextField txt_apellidoTrabajador;
    private javax.swing.JTextField txt_dvRutTrabajador;
    private javax.swing.JTextField txt_nacionalidad;
    private javax.swing.JTextField txt_nombreTrabajador;
    private javax.swing.JTextField txt_rutTrabajador;
    // End of variables declaration//GEN-END:variables
}
