/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorUsuario;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Alfonso
 */
public class CrearUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_agregarTrabajador = new javax.swing.JLabel();
        img_cafeCorazon = new javax.swing.JLabel();
        lbl_pilisCoffee = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombreUsuario = new javax.swing.JTextField();
        txt_contrasena = new javax.swing.JTextField();
        chk_crearUsuario = new javax.swing.JCheckBox();
        chk_modificarContrasena = new javax.swing.JCheckBox();
        chk_eliminarUsuario = new javax.swing.JCheckBox();
        chk_darquitarPermisos = new javax.swing.JCheckBox();
        chk_ingresarTrabajador = new javax.swing.JCheckBox();
        chk_generarContrato = new javax.swing.JCheckBox();
        chk_generarFiniquito = new javax.swing.JCheckBox();
        chk_liquidaciones = new javax.swing.JCheckBox();
        chk_ventaDiaria = new javax.swing.JCheckBox();
        chk_modificarVentaDiaria = new javax.swing.JCheckBox();
        chk_informeVenta = new javax.swing.JCheckBox();
        chk_nuevoProducto = new javax.swing.JCheckBox();
        chk_cumpleanos = new javax.swing.JCheckBox();
        chk_administrarStock = new javax.swing.JCheckBox();
        chk_crearProveedor = new javax.swing.JCheckBox();
        btn_guardar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pili's Coffee | Crear usuario");
        setResizable(false);

        lbl_agregarTrabajador.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_agregarTrabajador.setText("Crear Usuario");

        img_cafeCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafeHeart.png"))); // NOI18N

        lbl_pilisCoffee.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_pilisCoffee.setForeground(new java.awt.Color(153, 51, 255));
        lbl_pilisCoffee.setText("Pili's Coffee");
        lbl_pilisCoffee.setMaximumSize(new java.awt.Dimension(1080, 1920));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Nombre de usuario:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Permisos:");

        txt_nombreUsuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txt_contrasena.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        chk_crearUsuario.setText("Crear usuario");

        chk_modificarContrasena.setText("Modificar contraseña");
        chk_modificarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_modificarContrasenaActionPerformed(evt);
            }
        });

        chk_eliminarUsuario.setText("Eliminar usuario");

        chk_darquitarPermisos.setText("Dar/Quitar permisos");

        chk_ingresarTrabajador.setText("Ingresar trabajador");

        chk_generarContrato.setText("Generar contrato");

        chk_generarFiniquito.setText("Generar finiquito");

        chk_liquidaciones.setText("Liquidaciones");

        chk_ventaDiaria.setText("Ingresar venta diaria");

        chk_modificarVentaDiaria.setText("Modificar venta diaria");

        chk_informeVenta.setText("Informe de venta");

        chk_nuevoProducto.setText("Nuevo producto");

        chk_cumpleanos.setText("Cumpleaños");

        chk_administrarStock.setText("Administrar stock");

        chk_crearProveedor.setText("Crear proveedor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_darquitarPermisos)
                                    .addComponent(chk_eliminarUsuario)
                                    .addComponent(chk_modificarContrasena)
                                    .addComponent(chk_crearUsuario)
                                    .addComponent(chk_ingresarTrabajador)
                                    .addComponent(chk_generarContrato))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk_informeVenta)
                                    .addComponent(chk_modificarVentaDiaria)
                                    .addComponent(chk_cumpleanos)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chk_generarFiniquito)
                                            .addComponent(chk_liquidaciones)
                                            .addComponent(chk_ventaDiaria))
                                        .addGap(9, 9, 9)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chk_crearProveedor)
                                            .addComponent(chk_nuevoProducto)
                                            .addComponent(chk_administrarStock)))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addComponent(txt_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chk_crearUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_modificarContrasena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_eliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk_darquitarPermisos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_generarFiniquito)
                            .addComponent(chk_nuevoProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_liquidaciones)
                            .addComponent(chk_administrarStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chk_ventaDiaria)
                            .addComponent(chk_crearProveedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chk_modificarVentaDiaria)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_ingresarTrabajador)
                    .addComponent(chk_informeVenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_generarContrato)
                    .addComponent(chk_cumpleanos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_agregarTrabajador)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img_cafeCorazon, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lbl_pilisCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_agregarTrabajador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(img_cafeCorazon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_pilisCoffee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        Usuario u = new Usuario();
        u.setUsername(txt_nombreUsuario.getText());
        u.setPassword(txt_contrasena.getText());
        if(chk_crearUsuario.isSelected())
            u.setCrearUsuario(true);
        if(chk_modificarContrasena.isSelected())
            u.setModificarContrasena(true);
        if(chk_eliminarUsuario.isSelected())
            u.setEliminarUsuario(true);
        if(chk_darquitarPermisos.isSelected())
            u.setDarquitarPermisos(true);
        if(chk_ingresarTrabajador.isSelected())
            u.setIngresarTrabajador(true);
        if(chk_generarContrato.isSelected())
            u.setGenerarContrato(true);
        if(chk_generarFiniquito.isSelected())
            u.setGenerarFiniquito(true);
        if(chk_liquidaciones.isSelected())
            u.setLiquidaciones(true);
        if(chk_ventaDiaria.isSelected())
            u.setIngresarVentaDiaria(true);
        if(chk_modificarVentaDiaria.isSelected())
            u.setModificarVentaDiaria(true);
        if(chk_informeVenta.isSelected())
            u.setInformeVenta(true);
        if(chk_nuevoProducto.isSelected())
            u.setNuevoProducto(true);
        if(chk_cumpleanos.isSelected())
            u.setCumpleanos(true);
        if(chk_administrarStock.isSelected())
            u.setAdministrarStock(true);
        
        ControladorUsuario ctrlUsuario = new ControladorUsuario();
        ctrlUsuario.crearNuevoUsuario(u);
        this.dispose();
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();

    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed


    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void chk_modificarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_modificarContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_modificarContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JCheckBox chk_administrarStock;
    private javax.swing.JCheckBox chk_crearProveedor;
    private javax.swing.JCheckBox chk_crearUsuario;
    private javax.swing.JCheckBox chk_cumpleanos;
    private javax.swing.JCheckBox chk_darquitarPermisos;
    private javax.swing.JCheckBox chk_eliminarUsuario;
    private javax.swing.JCheckBox chk_generarContrato;
    private javax.swing.JCheckBox chk_generarFiniquito;
    private javax.swing.JCheckBox chk_informeVenta;
    private javax.swing.JCheckBox chk_ingresarTrabajador;
    private javax.swing.JCheckBox chk_liquidaciones;
    private javax.swing.JCheckBox chk_modificarContrasena;
    private javax.swing.JCheckBox chk_modificarVentaDiaria;
    private javax.swing.JCheckBox chk_nuevoProducto;
    private javax.swing.JCheckBox chk_ventaDiaria;
    private javax.swing.JLabel img_cafeCorazon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_agregarTrabajador;
    private javax.swing.JLabel lbl_pilisCoffee;
    private javax.swing.JTextField txt_contrasena;
    private javax.swing.JTextField txt_nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
