/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Alfonso
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form mainWindowAdm
     */
    public MainWindow() {
        initComponents();
    }
    
    public MainWindow(Usuario usuario){
        initComponents();
        lbl_usuario.setText(usuario.getUsername().toUpperCase());
        if(!usuario.isCrearUsuario())
            mi_crearUsuario.setEnabled(false);
        if(!usuario.isModificarContrasena())
            mi_modificarContrasena.setEnabled(false);
        if(!usuario.isEliminarUsuario())
            mi_eliminarUsuario.setEnabled(false);
        if(!usuario.isDarquitarPermisos())
            mi_darquitarPrivilegios.setEnabled(false);
        if(!usuario.isIngresarTrabajador())
            mi_agregarTrabajador.setEnabled(false);
        if(!usuario.isGenerarContrato())
            mi_generarContrato.setEnabled(false);
        if(!usuario.isGenerarFiniquito())
            mi_generarFiniquito.setEnabled(false);
        if(!usuario.isLiquidaciones())
            mi_liquidaciones.setEnabled(false);
        if(!usuario.isIngresarVentaDiaria())
            mi_ingresarVtaDia.setEnabled(false);
        if(!usuario.isModificarVentaDiaria())
            mi_modificarVtaDia.setEnabled(false);
        if(!usuario.isInformeVenta())
            mi_informeVenta.setEnabled(false);
        if(!usuario.isCumpleanos())
            mi_cumpleanios.setEnabled(false);
        if(!usuario.isNuevoProducto())
            mi_nuevoProducto.setEnabled(false);
        if(!usuario.isAdministrarStock())
            mi_administrarStock.setEnabled(false);
        if(!usuario.isCrearProveedor())
            mi_crearProveedor.setEnabled(false);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_cafeCorazon = new javax.swing.JLabel();
        lbl_pilisCoffee = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        btn_cerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        remuneraciones = new javax.swing.JMenu();
        mi_agregarTrabajador = new javax.swing.JMenuItem();
        mi_generarContrato = new javax.swing.JMenuItem();
        mi_generarFiniquito = new javax.swing.JMenuItem();
        mi_liquidaciones = new javax.swing.JMenuItem();
        mi_cumpleanios = new javax.swing.JMenuItem();
        contabilidad = new javax.swing.JMenu();
        mi_ingresarVtaDia = new javax.swing.JMenuItem();
        mi_modificarVtaDia = new javax.swing.JMenuItem();
        mi_informeVenta = new javax.swing.JMenuItem();
        invetario = new javax.swing.JMenu();
        mi_nuevoProducto = new javax.swing.JMenuItem();
        mi_administrarStock = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenu();
        mi_crearProveedor = new javax.swing.JMenuItem();
        usuarios = new javax.swing.JMenu();
        mi_crearUsuario = new javax.swing.JMenuItem();
        mi_modificarContrasena = new javax.swing.JMenuItem();
        mi_eliminarUsuario = new javax.swing.JMenuItem();
        mi_darquitarPrivilegios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(639, 412));
        setResizable(false);
        getContentPane().setLayout(null);

        img_cafeCorazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafeHeart.png"))); // NOI18N
        getContentPane().add(img_cafeCorazon);
        img_cafeCorazon.setBounds(600, 50, 215, 245);

        lbl_pilisCoffee.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lbl_pilisCoffee.setText("Pili's Coffee");
        lbl_pilisCoffee.setMaximumSize(new java.awt.Dimension(1080, 1920));
        getContentPane().add(lbl_pilisCoffee);
        lbl_pilisCoffee.setBounds(610, 20, 183, 42);

        lbl_usuario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lbl_usuario);
        lbl_usuario.setBounds(10, 20, 170, 30);

        btn_cerrarSesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_cerrarSesion.setForeground(new java.awt.Color(255, 0, 204));
        btn_cerrarSesion.setText("Cerrar Sesion");
        btn_cerrarSesion.setFocusPainted(false);
        btn_cerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrarSesion);
        btn_cerrarSesion.setBounds(10, 50, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 600);

        remuneraciones.setText("Remuneraciones");
        remuneraciones.setBorderPainted(true);

        mi_agregarTrabajador.setText("Agregar trabajador");
        mi_agregarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_agregarTrabajadorActionPerformed(evt);
            }
        });
        remuneraciones.add(mi_agregarTrabajador);

        mi_generarContrato.setText("Generar contrato");
        mi_generarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_generarContratoActionPerformed(evt);
            }
        });
        remuneraciones.add(mi_generarContrato);

        mi_generarFiniquito.setText("Generar finiquito");
        remuneraciones.add(mi_generarFiniquito);

        mi_liquidaciones.setText("Liquidaciones");
        remuneraciones.add(mi_liquidaciones);

        mi_cumpleanios.setText("Cumpleaños");
        remuneraciones.add(mi_cumpleanios);

        menuBar.add(remuneraciones);

        contabilidad.setText("Contabilidad");
        contabilidad.setBorderPainted(true);

        mi_ingresarVtaDia.setText("Ingresar venta diaria");
        mi_ingresarVtaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ingresarVtaDiaActionPerformed(evt);
            }
        });
        contabilidad.add(mi_ingresarVtaDia);

        mi_modificarVtaDia.setText("Modificar venta diaria");
        mi_modificarVtaDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarVtaDiaActionPerformed(evt);
            }
        });
        contabilidad.add(mi_modificarVtaDia);

        mi_informeVenta.setText("Informe de venta");
        contabilidad.add(mi_informeVenta);

        menuBar.add(contabilidad);

        invetario.setText("Inventario");
        invetario.setBorderPainted(true);

        mi_nuevoProducto.setText("Nuevo producto");
        mi_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_nuevoProductoActionPerformed(evt);
            }
        });
        invetario.add(mi_nuevoProducto);

        mi_administrarStock.setText("Administrar Stock");
        mi_administrarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_administrarStockActionPerformed(evt);
            }
        });
        invetario.add(mi_administrarStock);

        menuBar.add(invetario);

        clientes.setText("Clientes");

        mi_crearProveedor.setText("Crear proveedor");
        mi_crearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_crearProveedorActionPerformed(evt);
            }
        });
        clientes.add(mi_crearProveedor);

        menuBar.add(clientes);

        usuarios.setText("Usuarios");

        mi_crearUsuario.setText("Crear usuario");
        mi_crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_crearUsuarioActionPerformed(evt);
            }
        });
        usuarios.add(mi_crearUsuario);

        mi_modificarContrasena.setText("Modificar contraseña");
        mi_modificarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_modificarContrasenaActionPerformed(evt);
            }
        });
        usuarios.add(mi_modificarContrasena);

        mi_eliminarUsuario.setText("Eliminar usuario");
        usuarios.add(mi_eliminarUsuario);

        mi_darquitarPrivilegios.setText("Dar/Quitar privilegios");
        usuarios.add(mi_darquitarPrivilegios);

        menuBar.add(usuarios);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_agregarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_agregarTrabajadorActionPerformed
      AgregarTrabajador ventana = new AgregarTrabajador();
      ventana.setVisible(true);
      ventana.setTitle("Pili's Coffee | Agregar trabajador");
    }//GEN-LAST:event_mi_agregarTrabajadorActionPerformed

    private void mi_generarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_generarContratoActionPerformed
        GenerarContrato ventana = new GenerarContrato();
        ventana.setVisible(true);
        ventana.setTitle("Pili's Coffee | Generar contrato");
    }//GEN-LAST:event_mi_generarContratoActionPerformed

    private void mi_crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_crearUsuarioActionPerformed
        CrearUsuario ventana = new CrearUsuario();
        ventana.setVisible(true);
        ventana.setTitle("Pili's Coffee | Crear usuario");
        
        
    }//GEN-LAST:event_mi_crearUsuarioActionPerformed

    private void mi_ingresarVtaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ingresarVtaDiaActionPerformed
        VentaDiaria ventana = new VentaDiaria();
        ventana.setVisible(true);
        ventana.setTitle("Pili's Coffee | Ingresar venta diaria");
    }//GEN-LAST:event_mi_ingresarVtaDiaActionPerformed

    private void mi_modificarVtaDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarVtaDiaActionPerformed
        ModificarVenta ventana = new ModificarVenta();
        ventana.setVisible(true);
        ventana.setTitle("Pili's Coffee | Modificar venta diaria");
    }//GEN-LAST:event_mi_modificarVtaDiaActionPerformed

    private void btn_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSesionActionPerformed
        int cerrar=JOptionPane.showConfirmDialog(this, "CERRAR SESION?");
        if(cerrar == JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_btn_cerrarSesionActionPerformed

    private void mi_modificarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_modificarContrasenaActionPerformed
        ModificarContrasena ventana = new ModificarContrasena(lbl_usuario.getText().toUpperCase());
        ventana.setVisible(true);
        ventana.setTitle("Pili's Coffee | Modificar contraseña");
    }//GEN-LAST:event_mi_modificarContrasenaActionPerformed

    private void mi_nuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_nuevoProductoActionPerformed
        NuevoProducto ventana = new NuevoProducto();
        ventana.setVisible(true);
        ventana.setTitle("Pili's Coffee | Nuevo Producto");
    }//GEN-LAST:event_mi_nuevoProductoActionPerformed

    private void mi_administrarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_administrarStockActionPerformed
        AdministrarStock ventana = new AdministrarStock();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_administrarStockActionPerformed

    private void mi_crearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_crearProveedorActionPerformed
        CrearProveedor ventana = new CrearProveedor();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_crearProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarSesion;
    private javax.swing.JMenu clientes;
    private javax.swing.JMenu contabilidad;
    private javax.swing.JLabel img_cafeCorazon;
    private javax.swing.JMenu invetario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_pilisCoffee;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mi_administrarStock;
    private javax.swing.JMenuItem mi_agregarTrabajador;
    private javax.swing.JMenuItem mi_crearProveedor;
    private javax.swing.JMenuItem mi_crearUsuario;
    private javax.swing.JMenuItem mi_cumpleanios;
    private javax.swing.JMenuItem mi_darquitarPrivilegios;
    private javax.swing.JMenuItem mi_eliminarUsuario;
    private javax.swing.JMenuItem mi_generarContrato;
    private javax.swing.JMenuItem mi_generarFiniquito;
    private javax.swing.JMenuItem mi_informeVenta;
    private javax.swing.JMenuItem mi_ingresarVtaDia;
    private javax.swing.JMenuItem mi_liquidaciones;
    private javax.swing.JMenuItem mi_modificarContrasena;
    private javax.swing.JMenuItem mi_modificarVtaDia;
    private javax.swing.JMenuItem mi_nuevoProducto;
    private javax.swing.JMenu remuneraciones;
    private javax.swing.JMenu usuarios;
    // End of variables declaration//GEN-END:variables
}
